import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import RouteIcon from "./components/routeIcon"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex flex-col`}>
                <div className="upper h-16 w-full bg-slate-500">

                </div>
                <div className="flex h-full">
                    <div className="side flex flex-col min-w-14 bg-slate-400 h-full">
                        <RouteIcon title="Dashboard" to="dashboard" icon="ii.svg" />
                        <Link href="dashboard">dash</Link>
                        <Link href="errors">err</Link>
                        <Link href="recent">rec</Link>
                    </div>
                    <main>{children}</main>
                </div>
            </body>
        </html>
    )
}
